**Task Day-05**   
Task: Build a NumPy-Based Mini ML Engine for Linear Regression with
Synthetic Data.   

Objective:
Create a small Python app using NumPy that generates synthetic data, performs linear
regression using matrix operations, and supports saving/loading the data and model weights.

**Key Requirements (Mapped to Topics)**

**1) Linear Algebra Operations (ML-Relevant)**

• Use element-wise multiplication and dot product to compute predictions.

• Apply transpose and inverse for solving the Normal Equation:

2x+y = 3
x+3y = 4

• Use np.sum(np.diag(...)) to compute sum of diagonal elements in matrix
covariance.

• Use np.linalg.solve as an alternative method for solving linear systems.

**2) Random Number Generation**

• Use np.random.seed() for reproducibility.

• Use np.random.random() or np.random.randint() to generate synthetic feature data.

• Use np.random.choice() to randomly select samples for testing/training splits.

**3) NumPy I/O Operations**

• Save and load model weights using np.save() and np.load().

• Save the dataset to .txt format using np.savetxt() and load it back using
np.loadtxt().

• Use np.savez() to store multiple arrays in a single file, e.g., features, targets, and
weights.

**4) Arithmetic Operations and Array Slicing**

Apply vectorized arithmetic operations to perform statistical analysis.
Use slicing to separate train/test sets or to manipulate arrays during operations.

**Bonus (Optional)**

• Allow user input to choose between .npy, .txt, or .npz formats for saving data.

In [1]:
import numpy as np
# 1. Element-wise multiplication & dot product
# Example vectors
features = np.array([2, 3])
weights = np.array([0.5, 1.5])

# Element-wise multiplication
elementwise_product = features * weights
print("Element-wise multiplication:", elementwise_product)

# Dot product (prediction in ML)
dot_product = np.dot(features, weights)
print("Dot product (prediction):", dot_product)

# 2. Solving Linear System using Transpose & Inverse (Normal Equation)
# System of equations:
# 2x + y = 3
# x + 3y = 4

# Matrix form: AX = B
A = np.array([[2, 1],
              [1, 3]])
B = np.array([3, 4])

# Using inverse: X = A⁻¹B
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution using inverse:\n", X)

# 3. Sum of Diagonal Elements (Trace of Covariance Matrix)
# Example matrix (covariance-like)
matrix = np.array([[4, 2, 1],
                   [2, 5, 3],
                   [1, 3, 6]])

# Diagonal sum (trace)
trace = np.sum(np.diag(matrix))
print("Sum of diagonal elements (trace):", trace)

# 4. Solving Linear System using np.linalg.solve
# Same system: AX = B
X_alt = np.linalg.solve(A, B)
print("Solution using np.linalg.solve:\n", X_alt)


Element-wise multiplication: [1.  4.5]
Dot product (prediction): 5.5
Solution using inverse:
 [1. 1.]
Sum of diagonal elements (trace): 15
Solution using np.linalg.solve:
 [1. 1.]


In [2]:
# Random number generation

#seed for reproducibility
np.random.seed(42)

# Random data with 10 rows and 3 columns/features
synthetic_data = np.random.randint(0,100,size=(10,3))
print(synthetic_data)

# Selecting data randomly for training
indices =np.arange(10)
print(indices)
#lets assume we have 10 datasets
#Randomly select 70% (7 out of 10) for training
train_data_indices = np.random.choice(indices,size = 7,replace=False)
print(train_data_indices)
train_data = synthetic_data[train_data_indices]
print(train_data)
#Select rest of the data for testing
test_indices = np.setdiff1d(indices,train_data_indices )
test_data = synthetic_data[test_indices]
print(test_data)


[[51 92 14]
 [71 60 20]
 [82 86 74]
 [74 87 99]
 [23  2 21]
 [52  1 87]
 [29 37  1]
 [63 59 20]
 [32 75 57]
 [21 88 48]]
[0 1 2 3 4 5 6 7 8 9]
[1 5 4 8 0 7 6]
[[71 60 20]
 [52  1 87]
 [23  2 21]
 [32 75 57]
 [51 92 14]
 [63 59 20]
 [29 37  1]]
[[82 86 74]
 [74 87 99]
 [21 88 48]]


In [3]:
#Numpy I/O Operations
features = np.random.randint(0,100,size=(5,3))
targets = np.random.randint(0,2,size=(5,))
weights = np.random.random(size=(3,))

print("Features:\n", features)
print("Targets:\n", targets)
print("Weights:\n", weights)

np.save('model_weights.npy', weights)              # save weights
loaded_weights = np.load('model_weights.npy')      # load weights
print("\nLoaded Weights:\n", loaded_weights)

np.savetxt('features.txt', features, fmt='%d')      # save as text
loaded_features = np.loadtxt('features.txt', dtype=int)
print("\nLoaded Features from TXT:\n", loaded_features)

np.savez('model_data.npz', features=features, targets=targets, weights=weights)
data = np.load('model_data.npz')
print("\nLoaded from NPZ:")
print("Features:\n", data['features'])
print("Targets:\n", data['targets'])
print("Weights:\n", data['weights'])


Features:
 [[ 6 20 72]
 [38 17  3]
 [88 59 13]
 [ 8 89 52]
 [ 1 83 91]]
Targets:
 [0 1 0 1 0]
Weights:
 [0.83319491 0.17336465 0.39106061]

Loaded Weights:
 [0.83319491 0.17336465 0.39106061]

Loaded Features from TXT:
 [[ 6 20 72]
 [38 17  3]
 [88 59 13]
 [ 8 89 52]
 [ 1 83 91]]

Loaded from NPZ:
Features:
 [[ 6 20 72]
 [38 17  3]
 [88 59 13]
 [ 8 89 52]
 [ 1 83 91]]
Targets:
 [0 1 0 1 0]
Weights:
 [0.83319491 0.17336465 0.39106061]
