**Tasks Day -04**

**Mini Project:**
You are given daily sales data (in USD) of 6 products over 10 days. Perform the following tasks.

**Q1. Mathematical Operations**   

a. Calculate the total sales per product over 10 days.

b. Calculate the average daily sales per product.

c. Increase each sale by a 5% commission using broadcasting.

d. Apply the square root to all sales values (for testing purposes).

**Q2. Broadcasting Concepts**

a. Create a 1D and using broadcasting.

bonus_array = np.array([10, 20, 15, 25, 30, 5]) add it to each day’s sales

b. Add a $50 flat bonus to each sale using broadcasting.

**Q3. Statistical Analysis**

a. Find the mean, median, variance, and standard deviation of the entire dataset.

b. Find the maximum and minimum sale value and calculate the range.

c. Calculate the interquartile range (IQR) of all values.

**Q4. Logical & Comparison Operations**

a. Identify and list all sales greater than $250.

b. Replace all values greater than $300 with 300 (cap the max sale).

c. Count how many times sales were between $200 and  $250.

d. Create a new array showing only the sales below the mean.

**Q5. Searching, Sorting, and Final Summary**

a. Sort the sales of Day 5 in ascending order.

b. Find the day (row index) with the highest total sales.

c. Calculate column-wise means (average per product).

d. Calculate row-wise means (average per day).

e. Print the overall average sales.

**Q6. Bonus**

Create a function that returns all values 2 standard deviations above and below
the mean.

In [1]:
import numpy as np

sales_data = np.array([
    [200, 220, 250, 210, 180, 190],  # Day 1
    [230, 240, 260, 200, 195, 205],  # Day 2
    [210, 215, 255, 220, 185, 200],  # Day 3
    [205, 225, 275, 190, 195, 195],  # Day 4
    [215, 230, 265, 225, 200, 210],  # Day 5
    [225, 235, 275, 230, 205, 215],  # Day 6
    [235, 245, 280, 240, 210, 220],  # Day 7
    [245, 255, 290, 205, 215, 225],  # Day 8
    [255, 265, 300, 260, 220, 230],  # Day 9
    [265, 275, 310, 270, 225, 235]   # Day 10
])
print(sales_data)

#total sales per product over 10 days
# so we need column wise sum

print(np.sum(sales_data,axis =0))
print(np.mean(sales_data,axis=0))

final_sales = sales_data + (sales_data*5/100)
print(final_sales)

print(np.sqrt(sales_data))

[[200 220 250 210 180 190]
 [230 240 260 200 195 205]
 [210 215 255 220 185 200]
 [205 225 275 190 195 195]
 [215 230 265 225 200 210]
 [225 235 275 230 205 215]
 [235 245 280 240 210 220]
 [245 255 290 205 215 225]
 [255 265 300 260 220 230]
 [265 275 310 270 225 235]]
[2285 2405 2760 2250 2030 2125]
[228.5 240.5 276.  225.  203.  212.5]
[[210.   231.   262.5  220.5  189.   199.5 ]
 [241.5  252.   273.   210.   204.75 215.25]
 [220.5  225.75 267.75 231.   194.25 210.  ]
 [215.25 236.25 288.75 199.5  204.75 204.75]
 [225.75 241.5  278.25 236.25 210.   220.5 ]
 [236.25 246.75 288.75 241.5  215.25 225.75]
 [246.75 257.25 294.   252.   220.5  231.  ]
 [257.25 267.75 304.5  215.25 225.75 236.25]
 [267.75 278.25 315.   273.   231.   241.5 ]
 [278.25 288.75 325.5  283.5  236.25 246.75]]
[[14.14213562 14.83239697 15.8113883  14.49137675 13.41640786 13.78404875]
 [15.16575089 15.49193338 16.1245155  14.14213562 13.96424004 14.31782106]
 [14.49137675 14.6628783  15.96871942 14.83239697 13.60147

In [2]:
bonus_array = np.array([10, 20, 15, 25, 30, 5])
print(bonus_array)
print(bonus_array+sales_data)

print(sales_data+50)

[10 20 15 25 30  5]
[[210 240 265 235 210 195]
 [240 260 275 225 225 210]
 [220 235 270 245 215 205]
 [215 245 290 215 225 200]
 [225 250 280 250 230 215]
 [235 255 290 255 235 220]
 [245 265 295 265 240 225]
 [255 275 305 230 245 230]
 [265 285 315 285 250 235]
 [275 295 325 295 255 240]]
[[250 270 300 260 230 240]
 [280 290 310 250 245 255]
 [260 265 305 270 235 250]
 [255 275 325 240 245 245]
 [265 280 315 275 250 260]
 [275 285 325 280 255 265]
 [285 295 330 290 260 270]
 [295 305 340 255 265 275]
 [305 315 350 310 270 280]
 [315 325 360 320 275 285]]


In [3]:
mean = np.mean(sales_data)
Stddev = np.std(sales_data)
Variance = np.var(sales_data)
median = np.median(sales_data)
print(mean)
print(median)
print(Stddev)
print(Variance)

Max = np.max(sales_data)
Min = np.min(sales_data)
Range = Max - Min
print(Max)
print(Min)
print(Range)

Q1 = np.percentile(sales_data,25)
Q2 = np.percentile(sales_data,50)
Q3 = np.percentile(sales_data,75)
IQR = Q3-Q1
print(Q1)
print(Q2)
print(Q3)
print(IQR)

230.91666666666666
225.0
30.006827926693987
900.4097222222222
310
180
130
208.75
225.0
255.0
46.25


In [4]:
greater_than_250 = sales_data[(sales_data>250)]
print(greater_than_250)

capped_sales = np.copy(sales_data)
capped_sales[capped_sales > 300] = 300
print(capped_sales)


between_200and250 = sales_data[(sales_data>200) & (sales_data<250)]
print(between_200and250)
print(np.size(between_200and250))

new_arr = sales_data[(sales_data<np.mean(sales_data))]
print(new_arr)

[260 255 275 265 275 280 255 290 255 265 300 260 265 275 310 270]
[[200 220 250 210 180 190]
 [230 240 260 200 195 205]
 [210 215 255 220 185 200]
 [205 225 275 190 195 195]
 [215 230 265 225 200 210]
 [225 235 275 230 205 215]
 [235 245 280 240 210 220]
 [245 255 290 205 215 225]
 [255 265 300 260 220 230]
 [265 275 300 270 225 235]]
[220 210 230 240 205 210 215 220 205 225 215 230 225 210 225 235 230 205
 215 235 245 240 210 220 245 205 215 225 220 230 225 235]
32
[200 220 210 180 190 230 200 195 205 210 215 220 185 200 205 225 190 195
 195 215 230 225 200 210 225 230 205 215 210 220 205 215 225 220 230 225]


In [5]:
sorted_data = np.sort(sales_data[4])
print(sorted_data)

# to convert it into descending order
sorted_data[::-1]
print(sorted_data[::-1])

days_total = np.sum(sales_data, axis=1)
print(days_total)
max_day_index = np.argmax(days_total)
print(max_day_index)

#column-wise means
col = np.mean(sales_data, axis=0)
print(col)

#row-wise means
row = np.mean(sales_data, axis=1)
print(row)

overall_average = np.mean(sales_data)
print(overall_average)

[200 210 215 225 230 265]
[265 230 225 215 210 200]
[1250 1330 1285 1285 1345 1385 1430 1435 1530 1580]
9
[228.5 240.5 276.  225.  203.  212.5]
[208.33333333 221.66666667 214.16666667 214.16666667 224.16666667
 230.83333333 238.33333333 239.16666667 255.         263.33333333]
230.91666666666666


In [6]:
def highlight_outliers(arr):
     below = np.mean(arr.flatten()) - (2*np.std(arr.flatten()))
     above = np.mean(arr.flatten()) + (2*np.std(arr.flatten()))
     print(above)
     print(below)
     return arr[(arr<below) | (arr>above)]


highlight_outliers(sales_data)

290.93032252005463
170.90301081327868


array([300, 310])